### ISSUE TITLE
部署工具:kargo

### ISSUE THREAD

**Issue by Tonyzhangl** [feiskyer/kubernetes-handbook#1]
博主，不知道您使用kargo没，虽然用kargo有时在网络不稳定情况下会出篓子，不过个人感觉在规模量大的时候，kargo部署起来还是有利处的，之前听说 kargo 在做 etcd 高可用的话架构方案不是特别好，不知道博主怎么理解这部分的，如果有机会向博主交流学习下。感谢博主做的这部分分享，个人发现一些可能拼写失误导致的汉子打错，已经在gitbook中提了些commit了。

**Comment by feiskyer** [comment]
Sorry，kargo用的不多。etcd的高可用的话，etcd的[官方文档](https://coreos.com/etcd/docs/latest/v2/clustering.html)和[etcd operator](https://github.com/coreos/etcd-operator)都是不错的方案。

@Tonyzhangl 有没有兴趣写一个kargo的使用方法？

**Comment by Tonyzhangl** [comment]
@feiskyer  嗯，好的，博主。 我目前做了这块，可以完善下

**Comment by feiskyer** [comment]
@Tonyzhangl Thanks.
