### ISSUE TITLE
http://feisky.xyz/kubernetes/monitor/prometheus.txt 无法访问

### ISSUE THREAD

**Issue by xlgao-zju** [feiskyer/kubernetes-handbook#111]
[这个文件里面](https://github.com/feiskyer/kubernetes-handbook/blob/master/monitor/index.md)的`kubectl create -f http://feisky.xyz/kubernetes/monitor/prometheus.txt`链接无法访问了。

**Comment by feiskyer** [comment]
@xlgao-zju thanks, fixed.

**Comment by xlgao-zju** [comment]
@feiskyer Cool!
