### ISSUE TITLE
when i run gitbook build got unexpected token: . error

### ISSUE THREAD

**Issue by yudar1024** [feiskyer/kubernetes-handbook#117]
error: error while generating page "apps/helm-basic.md":

Template render error: 
\kubernetes-handbook\apps\helm-basic.md) [Line 112, Column 19]
  unexpected token: .

**Comment by feiskyer** [comment]
Didn't reproduce the problem. Did you run the build on the latest update? e.g. just run `make` in root dir of kubernetes-handbook.
