### ISSUE TITLE
根据提供的client-go informer示例,在处理多种资源时,会出现资源不同步的问题

### ISSUE THREAD

**Issue by wangweihong** [feiskyer/kubernetes-handbook#120]
参考案例提供的例子,在使用informer list-watch 12种资源时,在一开始的同步过程,发现直接是触发了集群已有资源的Create事件,但并非所有监听的资源都触发了该事件,导致客户端缓存的数据和集群的数据不同步.

**Comment by feiskyer** [comment]
> 并非所有监听的资源都触发了该事件

哪种资源没有加到客户端缓存里面？还真没碰到过，一般情况下不会在同一个程序里面同时监听过多的资源。

**Comment by wangweihong** [comment]
@feiskyer  谢谢你的回应.今天重新编写了测试程序,在一个Controller中添加了所有常用资源进行监听,返回来的数据正常.看起来应该是我之的前程序在Create事件触发回调函数处理有误,导致部分资源情况丢失的出现. 另外,我也参考了kube-controller-manager的代码, 准备拆分我写的Controller

**Comment by feiskyer** [comment]
👍
