### ISSUE TITLE
Update dashbaord url

### ISSUE THREAD

**Issue by nianjiang** [feiskyer/kubernetes-handbook#125]
The url (https://git.io/kube-dashboard) is not working now.

See https://github.com/kubernetes/dashboard, it should been
`kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml`

**Comment by nianjiang** [comment]
https://github.com/feiskyer/kubernetes-handbook/pull/124

**Comment by feiskyer** [comment]
Fixed in #124.
