### ISSUE TITLE
关于deployment的回退，描述有误

### ISSUE THREAD

**Issue by dreadbird** [feiskyer/kubernetes-handbook#131]
在文档中的描述：
>[默认情况下，kubernetes会在系统中**保存前两次的**Deployment的rollout历史记录，以便你可以随时回退（你可以修改revision history limit来更改保存的revision数）。](https://github.com/feiskyer/kubernetes-handbook/blob/master/concepts/deployment.md#回退deployment)

官网描述如下：
> [By default, **all of the Deployment’s rollout history** is kept in the system so that you can rollback anytime you want (you can change that by modifying revision history limit).](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/)

**Comment by feiskyer** [comment]
@dreadbird thanks, fixed
