### ISSUE TITLE
May I add the link of kubernetes-the-hard-way to this book

### ISSUE THREAD

**Issue by kweisamx** [feiskyer/kubernetes-handbook#134]
I translate the [kubernetes-the-hard-way](https://github.com/kelseyhightower/kubernetes-the-hard-way) .

The [Link](https://github.com/kweisamx/Kubernetes-The-Hard-Way-ZH) is here.

The kubernetes-the-hard-way can help to understand of kubernetes deeply, so I translate it and hope this can help other people to read easily.

Thanks!

**Comment by feiskyer** [comment]
@kweisamx Excellent. Could you open a PR for it?

**Comment by feiskyer** [comment]
Hmm, maybe also make a Simplified Chinese version?

**Comment by kweisamx** [comment]
OK @feiskyer 
I will make another version for Simplified Chinese and send PR
Thx

**Comment by kweisamx** [comment]
@feiskyer Thanks for your merge, but the [link](https://feisky.gitbooks.io/kubernetes/deploy/kubernetes-the-hard-way.html)
can't render other sub link

**Comment by feiskyer** [comment]
@kweisamx Oh, yep. should be fixed now.

**Comment by feiskyer** [comment]
gitbook requires link of html files, while github requires link of source file (markdown). Same difficult to make both work

**Comment by kweisamx** [comment]
Ok @feiskyer , if need any help that I can handle , just call me .

**Comment by feiskyer** [comment]
@kweisamx Links fixed. Thanks of excellent contribution
