### ISSUE TITLE
关于traefik的dashboard问题

### ISSUE THREAD

**Issue by pengyan2018** [feiskyer/kubernetes-handbook#142]
@feiskyer 你好，想问一下“安装traefik ingress”里面提到的“我查看到traefik的pod在172.20.0.115这台节点上启动了。 访问该地址http://172.20.0.115:8580/将可以看到dashboard”。这个172.20.0.115是指pod的ip还是指运行这个pod的主机的IP？

**Comment by feiskyer** [comment]
@pengyan2018 谢谢反馈，这里确实描述不清楚。 Dashboard 有两种方式可以访问，一是通过 NodeIP:NodePort 来访问，另一个是通过 UI Ingress。具体访问方法可以参考更新后的 Traefik 文档: https://github.com/feiskyer/kubernetes-handbook/blob/master/practice/service-discovery-lb/service-discovery-and-load-balancing.md

**Comment by pengyan2018** [comment]
@feiskyer 感谢回复！已知悉
