### ISSUE TITLE
安装步骤还是基于1.6，能更新到1.8上么？

### ISSUE THREAD

**Issue by doterme** [feiskyer/kubernetes-handbook#148]
如题

**Comment by feiskyer** [comment]
https://github.com/feiskyer/kubernetes-handbook/blob/master/deploy/kubernetes-the-hard-way.md 这里已经是 1.8 版本了

**Comment by doterme** [comment]
@feiskyer 那CentOS下的安装文档呢？

**Comment by feiskyer** [comment]
CentOS的文档还是1.6的，近期没有更新。现在更推荐使用kubeadm、kubespray等工具来部署

**Comment by doterme** [comment]
kubeadm不是不建议用在生产环境么？

**Comment by feiskyer** [comment]
kubeadm 现在已经是 beta 了，可以考虑使用了。
