### ISSUE TITLE
关于GitHub 存在的两个kubernetes-handbook项目的疑问

### ISSUE THREAD

**Issue by ToQuery** [feiskyer/kubernetes-handbook#159]
## 目前GitHub 存在两个 kubernetes-handbook

- https://github.com/rootsongjc/kubernetes-handbook
- https://github.com/feiskyer/kubernetes-handbook

这两个项目有什么联系，还是完全独立的两个项目？

**Comment by feiskyer** [comment]
独立的两个项目
