### ISSUE TITLE
English content is missing

### ISSUE THREAD

**Issue by snpdev** [feiskyer/kubernetes-handbook#160]
Hi. This looks like a wonderful resource, but  unfortunately the English content is missing. 

https://kubernetes.feisky.xyz/en/ has a link only to the introduction page, and the links from https://github.com/feiskyer/kubernetes-handbook/blob/master/en/SUMMARY.md return 404 errors.

**Comment by snpdev** [comment]
I see now that there is one section of English content at https://github.com/feiskyer/kubernetes-handbook/blob/master/en/troubleshooting/index.md.

I recommend that the English [README.md](https://github.com/feiskyer/kubernetes-handbook/tree/master/en) and [SUMMARY.md](https://github.com/feiskyer/kubernetes-handbook/blob/master/en/SUMMARY.md)   pages make it clear that only the Troubleshooting content is translated into English. Otherwise visitors will be confused.

Thank for your contribution. The Troubleshooting content is excellent.

**Comment by feiskyer** [comment]
@snpdev Thanks. I'm still working on the remaining part, and you're right. I should update SUMMARY to only include existing contents.
