### ISSUE TITLE
关于最新版本的pdf

### ISSUE THREAD

**Issue by or0or1** [feiskyer/kubernetes-handbook#165]
@feiskyer 最新版本的，有计划提供一下pdf文件不？ 谢谢

**Comment by echokk11** [comment]
@feiskyer 能问下你教程里画流程图和结构图的工具是什么吗

**Comment by feiskyer** [comment]
PlantUML

**Comment by or0or1** [comment]
@feiskyer  ths

**Comment by vsxen** [comment]
https://github.com/feiskyer/kubernetes-handbook/blame/master/zh/network/network.md#L8 
跨主机的pod也不需要NAT么？

**Comment by feiskyer** [comment]
@vsxen 是的，这是 Kubernetes 网络的基本特征
