### ISSUE TITLE
hostPath 和 Local Storage  持久化有什么区别？

### ISSUE THREAD

**Issue by songhe2136** [feiskyer/kubernetes-handbook#172]
老师： 我想问一下。hostPath 和 Local Storage  持久化有什么区别？
这两种方式都是持久化存储的方式。不知道有啥区别，使用场景上怎么区分。

**Comment by feiskyer** [comment]
hostPath 不跟 Node 绑定，这样 Pod 重新创建后有可能调度到其他 Node 上（有可能没有数据）；Local PV 跟 Node 绑定，重新调度还会到相同的 Node 上。

**Comment by songhe2136** [comment]
Local PV 跟 Node 绑定，如果我把一块盘做成 Local PV， 像 zk 这种需要分布式存储的服务，我使用 这块盘pv 持久化zk 的数据，这块盘坏了，数据就没了。

**Comment by songhe2136** [comment]
Local：
Local 是Kubernetes集群中每个节点的本地存储。这句话是翻译的官方的文档。他说是每个节点的本地存储。是我理解错了吗？
本地数据卷可以直接以持久化的方式使用（它总是通过 NodeAffinity 调度在某个指定的节点上）。

**Comment by feiskyer** [comment]
Local PV 是需要你手动创建的，在创建的时候绑定 Node。

> Local 是Kubernetes集群中每个节点的本地存储。这句话是翻译的官方的文档。他说是每个节点的本地存储。是我理解错了吗？

是 PV 指定节点的本地存储，磁盘坏，数据会丢失，所以还需要使用的时候做好高可用，比如使用 RAID 等。

**Comment by Hyvi** [comment]
local PV 使用场景 有哪些？ 日志吗？
