### ISSUE TITLE
Dynamic和Static Persistent Volume的区别?

### ISSUE THREAD

**Issue by memory125** [feiskyer/kubernetes-handbook#173]
想知道Dynamic和Static Persistent Volume的区别

**Comment by feiskyer** [comment]
- Dynamic: 是指用 StorageClass 动态管理 PV 的创建和删除
- Static PV：是指静态去创建 PV，也就是需要根据 PV 的参数要求手动去创建 PV

静态 PV 主要用于引用已有的持久化存储，比如要去访问持久化存储里面已有的数据的时候。其余场景推荐使用 StorageClass 动态管理 PV，更容易维护。

**Comment by memory125** [comment]
非常感谢！Dynamic创建的可以动态扩容吗？Static创建的貌似不能扩容。

**Comment by feiskyer** [comment]
> Dynamic创建的可以动态扩容吗？Static创建的貌似不能扩容

这个要看具体的存储实现了。一般来说，存储从Node解绑后（比如 Pod 删除了）可以扩容，但也有存储支持在线扩容。

**Comment by memory125** [comment]
Ok,非常感谢！
