### ISSUE TITLE
gluster 持久存储的问题

### ISSUE THREAD

**Issue by songhe2136** [feiskyer/kubernetes-handbook#174]
我现在用gluster 做 storageclass 动态pv， heketi 管理 gluster 的 volume。 但是这种方式并不能创建 glusterfs  分布式复制卷，glusterfs 生产一般不是用 分布式复制卷吗。 用heketi 不支持这种卷类型，是我搞错了?

**Comment by feiskyer** [comment]
See https://github.com/heketi/heketi/issues/1175
