### ISSUE TITLE
关于cAdvisor

### ISSUE THREAD

**Issue by leo1971** [feiskyer/kubernetes-handbook#176]
kubelet中默认集成的cAdvisor在1.8以后就不在:4194端口暴露了，现在:10255/metrics/cadvisor上，而kubelet配置文件中的默认cadvisor-port的值为0。

希望有空修正下。

**Comment by feiskyer** [comment]
嗯 是的。有没有兴趣发个PR更新下？

**Comment by leo1971** [comment]
> 嗯 是的。有没有兴趣发个PR更新下？

问题不大，有时间我整理一下发个PR
