### ISSUE TITLE
Azure 的chart 镜像很不稳定，有办法给他们反馈吗？

### ISSUE THREAD

**Issue by ykfq** [feiskyer/kubernetes-handbook#194]
主要问题是这样的：

- http 的 mirror 偶尔会出现 404 无法访问；
- https 的 mirror 证书一会儿是 `*.akscn.io`, 一会儿是 `mirror.azure.cn`

![image](https://user-images.githubusercontent.com/20741596/54988867-49c77880-4ff2-11e9-8a82-cd1b2fdda97f.png)

**Comment by feiskyer** [comment]
@ykfq 谢谢，我们来看看是怎么回事。

**Comment by feiskyer** [comment]
@andyzhangx

**Comment by andyzhangx** [comment]
@ykfq 之前证书配的有些问题，现在可以了。`mirror.azure.cn` 的问题可以发issue 到 https://github.com/Azure/container-service-for-azure-china/tree/master/aks，谢谢

**Comment by ykfq** [comment]
没想到问对了地方 。非常感谢两位的快速响应，目前已经可以正常使用了。
