### ISSUE TITLE
Missing "apiVersion" in file kubernetes-handbook/examples/projected-volume.yaml

### ISSUE THREAD

**Issue by wangluochao902** [feiskyer/kubernetes-handbook#211]
Thanks for this helpful handbook. We are developing a tool to find potential bugs in Kubernetes configuration files. I found out a potential problem of the file [kubernetes-handbook/examples/projected-volume.yaml](https://github.com/feiskyer/kubernetes-handbook/blob/549e0e3c9ba0175e64b2d4719b5a46e9016d532b/examples/projected-volume.yaml#L20). There is no "apiVersion" at line 20. 
Also, I use "kubectl" to validate the file, after I run 

```kubectl apply -f kubernetes-handbook/examples/projected-volume.yaml --dry-run=true```

I got the following error:

```error: error validating "projected-volume.yaml": error validating data: apiVersion not set; if you choose to ignore these errors, turn validation off with --validate=false```

Note the `apiVersion' field at line [48 ](https://github.com/feiskyer/kubernetes-handbook/blob/549e0e3c9ba0175e64b2d4719b5a46e9016d532b/examples/projected-volume.yaml#L48)
Would you mind telling me it is a real error or not?

**Comment by feiskyer** [comment]
@wangluochao902 it's a bug, fixed now.
