### ISSUE TITLE
你好，麻烦问一下怎么参与这个项目？最近在研究helm和k8s调度方面的内容，很想参与这个项目

### ISSUE THREAD

**Issue by yan234280533** [feiskyer/kubernetes-handbook#22]

**Comment by feiskyer** [comment]
@yan234280533 源码都在这个github repo里面，欢迎提PR，[这个](https://github.com/feiskyer/kubernetes-handbook/blob/master/CONTRIBUTING.md)有个简单的说明

**Comment by yan234280533** [comment]
@feiskyer  好的，你邮箱多少，方便通过邮箱交互一下其他的联系方式吗

**Comment by feiskyer** [comment]
欢迎加我微信feisky

**Comment by yan234280533** [comment]
好
