### ISSUE TITLE
kube-proxy通信问题

### ISSUE THREAD

**Issue by liuke80** [feiskyer/kubernetes-handbook#229]
[source](https://github.com/feiskyer/kubernetes-handbook/blob/master/components/components.md)
kube-proxy不是和kubelet通信的吧

**Comment by feiskyer** [comment]
不是的，文档哪里有问题吗？

**Comment by liuke80** [comment]
kube-proxy不是和kubelet通信，应该是直接和apiserver通信的吧

![image](https://user-images.githubusercontent.com/6457175/98206480-ebf06600-1f74-11eb-9bbc-922aea5b340b.png)

**Comment by h3kme** [comment]
> [source](https://api.cloudflare.com/client/v4/zones/cd7d0123e3012345da9420df9514dad0.patch)
> kube-proxy不是和kubelet通信的吧
