### ISSUE TITLE
main.yml

### ISSUE THREAD

**Issue by h3k-me** [feiskyer/kubernetes-handbook#245]
name: Docker-lint
on:
push:
tags: production
branches:
- master
pull_request:
jobs:
Docker:
name: lint
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: docker stop
uses: docker volume ls -f dangling=true && docker volume rm $(docker volume ls -f dangling=true -q)
args: --timeout=10m
working-directory: ./root

**Comment by feiskyer** [comment]
@h3k-me I didn't get why those new issues and PRs for. Would close all of them.
