### ISSUE TITLE
对于k8s中requests和limits，这个可不可以来一个具体的描述啊

### ISSUE THREAD

**Issue by yan234280533** [feiskyer/kubernetes-handbook#25]
对于k8s中requests和limits，这个可不可以来一个具体的描述，之前有专门分析过一块，这一块理解起来还有些复杂，写个具体的描述可以方便大家理解这两个概念

**Comment by feiskyer** [comment]
嗯 是应该加一下，[k8s文档 ](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/)里面有专门的描述。

@yan234280533 有兴趣加一下吗

**Comment by yan234280533** [comment]
@feiskyer  有兴趣。 我加到哪个文件夹下比较合适呢

**Comment by feiskyer** [comment]
可以加到[Pod](https://github.com/feiskyer/kubernetes-handbook/blob/master/architecture/pod.md#资源限制)里面

**Comment by feiskyer** [comment]
@yan234280533 刚增加了requests和limits的简单说明🤝

**Comment by yan234280533** [comment]
@feiskyer  好
