### ISSUE TITLE
部署apiserver的时候碰到一个错误

### ISSUE THREAD

**Issue by yiqinguo** [feiskyer/kubernetes-handbook#27]
你好：
按照这个教程在部署的apiserver的时候出现了一个错误  unable to sync kubernetes service: Endpoints "kubernetes" is invalid: subsets[0].addresses[0].ip: Invalid value: "127.0.0.1": may not be in the loopback range (127.0.0.0/8)
请教一下这是什么错

**Comment by feiskyer** [comment]
@yiqinguo 可否说明安装哪个步骤部署的？在哪一步的时候报的这个错误？

**Comment by yiqinguo** [comment]
@feiskyer https://github.com/feiskyer/kubernetes-handbook/blob/master/deploy/centos/master-installation.md    就是这个步骤启动apiserver的时候报的错

**Comment by feiskyer** [comment]
@yiqinguo 有没有把172.20.0.113替换成你本地的IP？注意advertise-address不能是127.0.0.1

**Comment by yiqinguo** [comment]
@feiskyer 多谢我把地址改了以后重新生成证书那个问题没了   但是又出现了http: TLS handshake error from 172.17.0.2:46364: EOF  这样一个错误   这个跟docker0一个网段的ip 但是也不是docker0的ip，想问下访问这个ip是干什么用的

**Comment by feiskyer** [comment]
看起来像是某个容器的IP，可以找一下docker容器列表看看

**Comment by yiqinguo** [comment]
原来是我机器上残留的docker影响到了

**Comment by feiskyer** [comment]
@yiqinguo  [node安装](https://github.com/feiskyer/kubernetes-handbook/blob/master/deploy/centos/node-installation.md#创建-kubelet-的service配置文件)中增加了这个选项的说明

**Comment by yiqinguo** [comment]
@feiskyer 嗯 我看到文档说的那个/etc/kubernetes/kubelet.kubeconfig文件了  但是我这里不能自动生成后来我换成/root/.kube/config了
