### ISSUE TITLE
kataconda playground is no longer available

### ISSUE THREAD

**Issue by boliu83** [feiskyer/kubernetes-handbook#271]
In https://kubernetes.feisky.xyz/introduction/cluster#katacoda-playground,  kataconda playground is listed as one of the online environment for playing with kubernetes. CLick the link it will take you to this [notice](https://www.katacoda.com/courses/kubernetes/playground) says Kataconda has been permanently closed.  

The annoucement from O'Reily about closing Kataconde: https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html

**Comment by feiskyer** [comment]
thanks for reporting, updated contents.
