### ISSUE TITLE
Host "sz-pg-oam-docker-hub-001.tendcloud.com" is unavailable

### ISSUE THREAD

**Issue by sora-zero** [feiskyer/kubernetes-handbook#69]
In node-installation.md, **安装和配置 kubelet** section
The pod infrastructure container was set to `--pod-infra-container-image=sz-pg-oam-docker-hub-001.tendcloud.com`. But this host isn't available now. I think it would be better to use k8s's default value, at least that one is working.

**Comment by feiskyer** [comment]
@sora-zero Thanks. Fixed.
