### ISSUE TITLE
页面乱码

### ISSUE THREAD

**Issue by JinsYin** [feiskyer/kubernetes-handbook#76]
[Kubernetes部署指南](https://kubernetes.feisky.xyz/deploy/) 下 `在CentOS上部署kubernetes1.6集群` 中好几个子目录访问时都是出现了乱码，不确定是不是我个人浏览器原因；另外，这几个子目录都是 md 文件，不是 html 页面。

**Comment by feiskyer** [comment]
嗯 这几个页面没有链接到summary里面，所以没有编译成html。把它们链到github吧。
